trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs: 
  - job: FirstJob #no spaces while giving name
    steps:
    - bash: echo build first job
  - job: SecondJob #no spaces while giving name
    steps:
    - bash: echo build second job
- stage: DevDeploy
  dependsOn: Build
  jobs: 
  - job: DevDeployJob #no spaces while giving name
    steps:
    - bash: echo dev deploy job
- stage: QADeploy
  dependsOn: 
  - Build
  jobs: 
    - job: QADeployJob #no spaces while giving name
      steps:
      - bash: echo QA Deploy job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs: 
    - job: ProdDeployJob #no spaces while giving name
      steps:
      - bash: echo Prod Deploy job
