trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs: 
  - job: FirstJob     #no spaces while giving name
    steps:
    - bash: echo build first job
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourceDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
  # - job: SecondJob    #no spaces while giving name
  #   steps:
  #   - bash: echo build second job
# - stage: DevDeploy
#   variables:
#     environment: Dev 
#   dependsOn: Build
#   jobs: 
#   - job: DevDeployJob     #no spaces while giving name
#     steps:
#     - bash: echo $(environment) deploy job
# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: 
#   - Build
#   jobs: 
#     - job: QADeployJob #no spaces while giving name
#       steps:
#       - bash: echo $(environment)Deploy job
# - stage: ProdDeploy
#   variables:
#     environment: Prod
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs: 
#     - job: ProdDeployJob #no spaces while giving name
#       steps:
#       - bash: echo $(environment) Deploy job
